/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import java.sql.*;
import Dao.ConexaoBd;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Matheus
 */
public class AddUsuario extends javax.swing.JInternalFrame {

    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    public AddUsuario() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
        conexao = ConexaoBd.conector();

    }

    public void cadastrar() {

        String sql = "INSERT into usuarios(nome,numero,email,usuario,senha,perfil) VALUES (?,?,?,?,?,?)";
        try {
            pst = conexao.prepareStatement(sql);
            pst.setString(1, txtnome.getText());
            pst.setString(2, txtnumero.getText());
            pst.setString(3, txtemail.getText());
            pst.setString(4, txtusuario.getText());
            pst.setString(5, txtsenha.getText());
            pst.setString(6, perfilJ.getSelectedItem().toString());

            if ((txtnome.getText().isEmpty()) || (txtnumero.getText().isEmpty()) || (txtemail.getText().isEmpty()) || (txtusuario.getText().isEmpty()) || (txtsenha.getText().isEmpty())) {
                JOptionPane.showMessageDialog(null, "Preencha todos os campos Para Continuar");
            } else {
                int adicionar = pst.executeUpdate();
                if (adicionar > 0) {
                    JOptionPane.showMessageDialog(null,  txtnome.getText() +" Foi adicionado com sucesso!");
                    txtnome.setText(null);
                    txtnumero.setText(null);
                    txtemail.setText(null);
                    txtusuario.setText(null);
                    txtsenha.setText(null);
                    perfilJ.getSelectedIndex();
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ERRO: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new com.k33ptoo.components.KGradientPanel();
        txtnumero = new br.com.cyber.componente.KTextField();
        txtnome = new br.com.cyber.componente.KTextField();
        txtusuario = new br.com.cyber.componente.KTextField();
        txtemail = new br.com.cyber.componente.KTextField();
        txtsenha = new br.com.cyber.componente.KPasswordField();
        jLabel1 = new javax.swing.JLabel();
        kButton1 = new br.com.cyber.componente.KButton();
        perfilJ = new br.com.cyber.componente.KComboBox();
        mm = new javax.swing.JLabel();
        versenha = new javax.swing.JCheckBox();

        kGradientPanel1.setkBorderRadius(0);
        kGradientPanel1.setkEndColor(new java.awt.Color(0, 179, 225));
        kGradientPanel1.setkGradientFocus(900);
        kGradientPanel1.setkStartColor(new java.awt.Color(10, 113, 218));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtnumero.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        txtnumero.setK_obrigatory(true);
        txtnumero.setK_placeholder_text("Numero");
        txtnumero.setK_placeholder_text_color(new java.awt.Color(51, 51, 51));
        kGradientPanel1.add(txtnumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 188, 541, -1));

        txtnome.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        txtnome.setK_obrigatory(true);
        txtnome.setK_placeholder_text("Nome ");
        txtnome.setK_placeholder_text_color(new java.awt.Color(51, 51, 51));
        kGradientPanel1.add(txtnome, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 127, 541, -1));

        txtusuario.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        txtusuario.setK_obrigatory(true);
        txtusuario.setK_placeholder_text("Usuario");
        txtusuario.setK_placeholder_text_color(new java.awt.Color(51, 51, 51));
        kGradientPanel1.add(txtusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 310, 541, -1));

        txtemail.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        txtemail.setK_obrigatory(true);
        txtemail.setK_placeholder_text("Email");
        txtemail.setK_placeholder_text_color(new java.awt.Color(51, 51, 51));
        kGradientPanel1.add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 249, 541, -1));

        txtsenha.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        txtsenha.setK_obrigatory(true);
        txtsenha.setK_placeholder_text("Senha");
        txtsenha.setK_placeholder_text_color(new java.awt.Color(51, 51, 51));
        kGradientPanel1.add(txtsenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 363, 541, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Perfil");
        kGradientPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 80, -1, -1));

        kButton1.setText("Salvar");
        kButton1.setToolTipText("Adicionar novo usuário");
        kButton1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                kButton1MouseMoved(evt);
            }
        });
        kButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                kButton1MouseExited(evt);
            }
        });
        kButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton1ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(kButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(406, 438, 242, -1));

        perfilJ.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Atendente", "Administrador" }));
        perfilJ.setA_arrow_back_color(new java.awt.Color(0, 0, 0));
        perfilJ.setA_item_list_selected_back_color(new java.awt.Color(204, 204, 204));
        perfilJ.setA_item_list_selected_text_color(new java.awt.Color(0, 102, 255));
        perfilJ.setA_item_set_back(new java.awt.Color(0, 102, 204));
        perfilJ.setA_list_unselected_text_color(new java.awt.Color(51, 51, 51));
        perfilJ.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        perfilJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perfilJActionPerformed(evt);
            }
        });
        kGradientPanel1.add(perfilJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 74, -1, -1));

        mm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Form/olho_aberto_32.png"))); // NOI18N
        kGradientPanel1.add(mm, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 370, 30, 20));

        versenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                versenhaActionPerformed(evt);
            }
        });
        kGradientPanel1.add(versenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 370, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1138, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void perfilJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perfilJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_perfilJActionPerformed

    private void kButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton1ActionPerformed
        cadastrar();        // TODO add your handling code here:
    }//GEN-LAST:event_kButton1ActionPerformed

    private void versenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_versenhaActionPerformed
        if(versenha.isSelected()){
            txtsenha.setEchoChar((char)0);
            mm.setIcon(new javax.swing.ImageIcon(getClass().getResource("olho_fechado_32.png")));
        }else{
            txtsenha.setEchoChar('*');
            mm.setIcon(new javax.swing.ImageIcon(getClass().getResource("olho_aberto_32.png")));
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_versenhaActionPerformed

    private void kButton1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kButton1MouseMoved
   kButton1.setBackground(new Color(10,113,218));
   kButton1.setForeground(Color.white);
// TODO add your handling code here:
    }//GEN-LAST:event_kButton1MouseMoved

    private void kButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kButton1MouseExited
   kButton1.setBackground(new Color(240,240,240));
   kButton1.setForeground(Color.black);
                // TODO add your handling code here:
    }//GEN-LAST:event_kButton1MouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private br.com.cyber.componente.KButton kButton1;
    private com.k33ptoo.components.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel mm;
    private br.com.cyber.componente.KComboBox perfilJ;
    private br.com.cyber.componente.KTextField txtemail;
    private br.com.cyber.componente.KTextField txtnome;
    private br.com.cyber.componente.KTextField txtnumero;
    private br.com.cyber.componente.KPasswordField txtsenha;
    private br.com.cyber.componente.KTextField txtusuario;
    private javax.swing.JCheckBox versenha;
    // End of variables declaration//GEN-END:variables
}
