/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import java.awt.Color;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import java.sql.*;
import Dao.ConexaoBd;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Matheus
 */
public class ApagarProdutos extends javax.swing.JInternalFrame {

    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    public ApagarProdutos() {
        initComponents();
        conexao = ConexaoBd.conector();

        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
    }

    private void setar_campos() {
        int setar = tblEditar.getSelectedRow();
        txtID.setText(tblEditar.getModel().getValueAt(setar, 0).toString());
        txtnome.setText(tblEditar.getModel().getValueAt(setar, 1).toString());
        txtpreco.setText(tblEditar.getModel().getValueAt(setar, 2).toString());
        txtdescricao.setText(tblEditar.getModel().getValueAt(setar, 3).toString());
    }

    public void Deletar() {
        int confirma = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja excluir este Usuario? ", "Atenção", JOptionPane.YES_NO_OPTION);
        if (confirma == JOptionPane.YES_OPTION) {
            String sql = "Delete from produtos where Codico=?";
            try {
                pst = conexao.prepareStatement(sql);
                pst.setString(1, txtID.getText());
                int apagado = pst.executeUpdate();
                if (apagado > 0) {
                    JOptionPane.showMessageDialog(null, "Usuario Apagado");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "ERRO: " + e.getMessage());
            }
        }
    }

    private void PesquisarNome() {

        String sql = "Select *from produtos where nome like ?";
        try {
            pst = conexao.prepareStatement(sql);
            pst.setString(1, nomePesq.getText() + "%");
            rs = pst.executeQuery();
            tblEditar.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ERRO: " + e.getMessage());
        }
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new com.k33ptoo.components.KGradientPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEditar = new br.com.cyber.componente.Ktable();
        nomePesq = new br.com.cyber.componente.KTextField();
        txtnome = new javax.swing.JTextField();
        txtdescricao = new javax.swing.JTextField();
        txtpreco = new javax.swing.JTextField();
        kButton1 = new br.com.cyber.componente.KButton();
        txtID = new javax.swing.JTextField();

        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        kGradientPanel1.setkBorderRadius(0);
        kGradientPanel1.setkEndColor(new java.awt.Color(0, 179, 225));
        kGradientPanel1.setkStartColor(new java.awt.Color(10, 113, 208));
        kGradientPanel1.setLayout(null);

        tblEditar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEditarMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblEditar);

        kGradientPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 290, 1000, 300);

        nomePesq.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        nomePesq.setK_placeholder_text("Pesquisar Nome ");
        nomePesq.setK_placeholder_text_color(new java.awt.Color(51, 51, 51));
        nomePesq.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nomePesqKeyReleased(evt);
            }
        });
        kGradientPanel1.add(nomePesq);
        nomePesq.setBounds(50, 250, 737, 30);

        txtnome.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        txtnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomeActionPerformed(evt);
            }
        });
        kGradientPanel1.add(txtnome);
        txtnome.setBounds(50, 25, 580, 30);

        txtdescricao.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        kGradientPanel1.add(txtdescricao);
        txtdescricao.setBounds(50, 123, 580, 120);

        txtpreco.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        txtpreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprecoActionPerformed(evt);
            }
        });
        kGradientPanel1.add(txtpreco);
        txtpreco.setBounds(50, 70, 580, 30);

        kButton1.setText("Apagar");
        kButton1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                kButton1MouseMoved(evt);
            }
        });
        kButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                kButton1MouseExited(evt);
            }
        });
        kButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton1ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(kButton1);
        kButton1.setBounds(679, 195, 200, 34);
        kGradientPanel1.add(txtID);
        txtID.setBounds(709, 129, 54, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1021, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 596, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEditarMouseClicked
        setar_campos();        // TODO add your handling code here:
    }//GEN-LAST:event_tblEditarMouseClicked

    private void nomePesqKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomePesqKeyReleased
        PesquisarNome();
        //TODO add your handling code here:
    }//GEN-LAST:event_nomePesqKeyReleased

    private void txtnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomeActionPerformed

    private void txtprecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprecoActionPerformed

    private void kButton1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kButton1MouseMoved
        kButton1.setBackground(new Color(10, 113, 218));
        kButton1.setForeground(Color.white);          // TODO add your handling code here:
    }//GEN-LAST:event_kButton1MouseMoved

    private void kButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kButton1MouseExited
        kButton1.setBackground(new Color(240, 240, 240));
        kButton1.setForeground(Color.black);       // TODO add your handling code here:
    }//GEN-LAST:event_kButton1MouseExited

    private void kButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton1ActionPerformed
        Deletar();
        txtID.setText(null);
        txtpreco.setText(null);
        txtdescricao.setText(null);
        txtnome.setText(null);
        PesquisarNome();

        // TODO add your handling code here:
    }//GEN-LAST:event_kButton1ActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
    PesquisarNome();     
txtID.setEnabled(false);
txtID.setVisible(false);
txtnome.setEnabled(false);
txtdescricao.setEnabled(false);
txtpreco.setEnabled(false);
// TODO add your handling code here:
    }//GEN-LAST:event_formInternalFrameOpened


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private br.com.cyber.componente.KButton kButton1;
    private com.k33ptoo.components.KGradientPanel kGradientPanel1;
    private br.com.cyber.componente.KTextField nomePesq;
    private br.com.cyber.componente.Ktable tblEditar;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtdescricao;
    private javax.swing.JTextField txtnome;
    private javax.swing.JTextField txtpreco;
    // End of variables declaration//GEN-END:variables
}
